### ISSUE TITLE
OIDC Login redirect_uri is incorrect using Generic Kubernetes 1.28.6 cluster

### ISSUE THREAD

**Issue by jonathanracine** [stackrox/stackrox#10733]
We upgrade our Stackrox instance to the latest stable release, but unfortunately, this seemed to have broken the OIDC authentication flow.
Current configuration
Kubernetes v1.28.6
Istio v1.21.1, using the Kubernetes Gateway API

Expected Behavior:
When the user Logs In using an OIDC provider, the "redirect_uri" should be set to the base URL of the Stackrox instance :
https://my.oidc.server.tld/oauth2/authorize?client_id=...&redirect_uri=https://**my.stackrox.validdomain.com**/auth/response[...]

Current Behavior :
The redirect URI for the OIDC login call gets written as :
https://my.oidc.server.tld/oauth2/authorize?client_id=...&redirect_uri=https://**localhost:64147**/auth/response[...]

Workarounds tried :
Istio was fully disabled from the Stackrox Namespace, and Port forwarding using the http connection was tried, without much luch

I modified the Stackrox Helm chart with using "central.exposure.loadBalancer: true". This created a endpoint fully bypassing any issues that would come from Istio/K8S Gateway; We are now connected directly to Stackrox's instance. I still see the URL being rewritten to localhost instead of keeping the original domain.

If I manually edit the the HTTP query sent to my OIDC server and replace the "localhost" string with the proper stackrox fqdn, the OIDC authentication flow proceeds properly and I can log back to the server.

Additional notes :
The OIDC provider we are using currently supports Fragment or Query mode

**Comment by dhaus67** [comment]
Hey, thanks for filing the issue.

Couple of clarifying questions: 
- from which version did you upgrade from?
- in your OIDC provider, which redirect_uri is configured for the OIDC client you're using for the Stackrox instance? Is it `my.stackrox.validdomain.com`?

And as a side-note, do you mind sharing the API response from `/v1/authProviders`? The fields I'm specifically interested in within your auth provider would be:
```json
{
  "uiEndpoint": "",
  "extraUIEndpoints": [],
}
```

I will dig deeper to check out whether there's a regression.

As a possible culprit (to be confirmed based on the questions I asked): 
An auth provider has a `uiEndpoint` set to the hostname which was used when the auth provider was created. This is used to verify the redirect URL and will be used as default, if no other valid host name is added to the auth provider.

Adding this to the auth provider requires you to either create the auth provider via API (since the `extraUIEndpoints` aren't exposed within the UI as configuration option) or via declarative configuration (see [here for more information on that topic as well as examples](https://docs.openshift.com/acs/4.4/configuration/declarative-configuration-using.html#declarative-config-example-auth-provider)).
You'd need to add the `my.stackrox.validdomain.com` within the list of `extraUIEndpoints` this way during redirect the host would be accepted by Central and redirect you properly to `my.stackrox.validdomain.com`.

**Comment by jonathanracine** [comment]
Hi,
We upgraded from release 4.3.5 to 4.4.0.

We defined 2 redirect URI in our OIDC provider :
https://my.stackrox.validdomain.com/sso/providers/oidc/callback
https://my.stackrox.validdomain.com/auth/response/oidc

Here is my auth Provider configuration :
{"authProviders":[{"id":"805c1c74-99ee-4bbd-b88e-24f75d7515f2","name":"SAP OIDC","type":"oidc","uiEndpoint":"localhost:64147","enabled":true,"config":{"client_id":"<redacted>","client_secret":"","issuer":"https://observability.accounts.<redacted>.com","mode":"fragment"},"loginUrl":"/sso/login/<redacted>","validated":false,"extraUiEndpoints":[],"active":false,"requiredAttributes":[],"traits":{"mutabilityMode":"ALLOW_MUTATE","visibility":"VISIBLE","origin":"IMPERATIVE"},"claimMappings":{},"lastUpdated":"2024-04-08T16:15:45.932873107Z"},{"id":"4df1b98c-24ed-4073-a9ad-356aec6bb62d","name":"Login with username/password","type":"basic","uiEndpoint":"","enabled":true,"config":{},"loginUrl":"/sso/login/4df1b98c-24ed-4073-a9ad-356aec6bb62d","validated":true,"extraUiEndpoints":[],"active":true,"requiredAttributes":[],"traits":null,"claimMappings":{},"lastUpdated":null}]}

The information you provided is indeed helpful, as I can see the uiEndpoint is not configured with the proper data

**Comment by dhaus67** [comment]
Thanks for the answer - that looks like the culprit for the time being.

Can you try to re-create the auth provider with the `extraUIEndpoints` field containig your `my.stackrox.validdomain.com` hostname? Via API you will find the API docs _within_ your Central (clicking the `?` in the top right corner), you will be looking for `AuthProviderService_PostAuthProvider`. If you want to go the declarative route, I've linked the samples for you in the previous comment.

**Comment by jonathanracine** [comment]
Hi,
Re-creating the auth provider indeed worked! Thanks a lot for the help!

However : I wasn't able to delete the "broken" auth provider for some reasons, so I went in the database and deleted it from the authprovider table. Our system is now fully operational.

If time permits it, I will create a PR on the helm examples folder, with all the steps I took to get this deployment to work with Kubernetes Gateway
