### ISSUE TITLE
CVEs found in roxctl 4.4.2

### ISSUE THREAD

**Issue by yyuanxin** [stackrox/stackrox#11309]
Hi, our team is running a trivy scan on the roxctl 4.4.2.
From the trivy scan, we found the following CVEs
- CVE-2019-25210
- CVE-2024-24557

The details of the respective CVEs:
<img width="1064" alt="image" src="https://github.com/stackrox/stackrox/assets/50551313/bf6d0be8-189e-4726-9058-c2648550fbe5">

We would like to seek any advice regarding the status of the CVEs found.
Thank you!

**Comment by RTann** [comment]
According to the Helm maintainers, CVE-2019-25210 is not a real vulnerability: https://helm.sh/blog/response-cve-2019-25210/

https://osv.dev/vulnerability/GHSA-xw73-rw38-6vjc makes it seem like we are only vulnerable to CVE-2024-24557 if we build images, which the `roxctl` image does not do

**Comment by RTann** [comment]
A future version of StackRox will use an invulnerable version of `github.com/docker/docker` - https://github.com/stackrox/stackrox/blob/master/go.mod#L209 (at least, invulnerable to CVE-2024-24557)

Since the Helm maintainers do not see CVE-2019-25210, my guess is that package will never be "fixed", but it looks like v3.15.0 adds an option to hide secrets in dry runs. That being said, I do not believe we even use this functionality, especially in this particular image
