### ISSUE TITLE
Failed to get EKS cluster metadata from instance tags: getting cluster name tag: EC2MetadataError: failed to make EC2Metadata request

### ISSUE THREAD

**Issue by jseiser** [stackrox/stackrox#11719]
Our Sensor pods are throwing this error.

```
root logger: 2024/06/25 21:43:33.834724 logger.go:75: Error: pkg/cloudproviders/aws/metadata.go:142 - Failed to get EKS cluster metadata from instance tags: getting cluster name tag: EC2MetadataError: failed to make EC2Metadata request
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>

	status code: 404, request id: 
root logger: 2024/06/25 21:43:33.860312 logger.go:75: Error: pkg/cloudproviders/aws/metadata.go:156 - Failed to get EKS cluster metadata from node labels: node label "alpha.eksctl.io/cluster-name" not found
```

Im not sure what/why its looking for a label of `alpha.eksctl.io/cluster-name`, since this cluster is not deployed with eksctl.  The metadata call I assume fails because stackrox is using IMDSv1, instead of IMDSv2.  If it wants to query for tags using the AWS API, I am not seeing any documentation in the helm chart for adding IRSA annotations to a specific service account.

Can anyone clear up what this is expecting to be in place?

**Comment by stehessel** [comment]
Hi @jseiser,
Sensor attempts to read out cloud provider meta provider heuristically and on a best effort basis. For AWS, it attempts to determine the cluster type based on EC2 instance tags or node labels. It looks like in your case Sensor was not able to find these tags/labels. These tags are not always set and sometimes inaccessible, which is okay. I believe in these cases we should just log on debug level instead of error level to avoid confusion. I created https://github.com/stackrox/stackrox/pull/11724 for this.
