### ISSUE TITLE
Differences between Stackrox open source and the enterprise version

### ISSUE THREAD

**Issue by ccodreanu** [stackrox/stackrox#2100]
Hi!

I was trying to get more info about the differences between this project and the enterprise version.

How should the deployment be done for this project. `stackrox.io/main:3.70.0` requires auth to the registry.

Moreover, are any of the features dropped in the open source version?

Is there on the roadmap to have public container images?

Many thanks!

**Comment by Maddosaurus** [comment]
Hi @ccodreanu!

Thanks for stopping by!
Could you share with me where you found the `stackrox.io/main:3.70.0` image tag? 
Because that is definitely an out-of-date location and we need to update our public facing information 😄 

Let me start by answering the question of deployment:
We provide Helm charts (see https://github.com/stackrox/stackrox#quick-installation-via-helm for a quick start) and public container images hosted at https://quay.io/stackrox-io. These will install the latest stable version (3.70.0 as of today) without any registry auth.
If you want to compile and deploy the latest master yourself, we also have deployment scripts for that (see https://github.com/stackrox/stackrox#development ).

As to the differences:
The main difference is the product branding (Red Hat ACS vs. StackRox) and of course the support.
The enterprise version is well integrated into the Red Hat ecosystem, and has additional installation options (right now, namely the [ACS Operator](https://docs.openshift.com/acs/installing/install-ocp-operator.html)).
As of today, all features are available in both versions.

**Comment by crimv42** [comment]
@Maddosaurus is this still the case? Even when using the helm chart you have listed, im still getting an unauthorized error on the image pull
