### ISSUE TITLE
CVE Scanning for node not possible

### ISSUE THREAD

**Issue by balpert89** [stackrox/stackrox#2676]
Hi,

OCP Version - Central: 4.9.33
OCP Version - Secured Cluster: 4.10.20, 4.9.33, 4.8.19
Stackrox Version: 3.71.0

we are deploying Stackrox on OCP4. The Vulnerability Management Details page for a node of a secured cluster does not show any CVE Data, instead I can only see a message 
```
CVE DATA MAY BE INACCURATE
Node unsupported.
Scanning this node is not supported at this time. Please see the release notes for more information.
```
Question 1: where can I find the release notes?
Question 2: is there a roadmap for new features? E.g. I saw #2588 for example and am wondering when to expect this in a versioned release
Question 3: how can I enable scans for CoreOS nodes?

![image](https://user-images.githubusercontent.com/28100685/183901902-2e14a9b9-476a-42ae-9354-daef436af2ad.png)

**Comment by rukletsov** [comment]
@jvdm could you please chime in here?

**Comment by jvdm** [comment]
@balpert89 CoreOS node scanning is currently disabled because some of the CVE sources we use for node scanning are not OS-specific. Instead, we use NVD, despite the fact that Red Hat OVALs offer more accurate information. To avoid confusion, it was disabled.

The release notes refer to [RHACS release notes for 3.71](https://docs.openshift.com/acs/3.70/release_notes/370-release-notes.html). In Stackrox, they are somewhat tracked in the [Changelog for 3.70](https://github.com/stackrox/stackrox/blob/master/CHANGELOG.md#700). Sorry for the confusion. Stackrox is currently highly tied with RHACS, so some of the information can only be seen downstream.

The [notes](https://docs.openshift.com/acs/3.70/release_notes/370-release-notes.html#vuln-scanning-rhcos-rn) say:

> Vulnerability scanning and reporting for Red Hat Enterprise Linux CoreOS (RHCOS) nodes has been disabled until scanning improvements are made for improved accuracy and to support full host-level scanning beyond just Kubernetes components. Currently, RHCOS uses National Vulnerability Database (NVD) vulnerability data for reporting vulnerabilities for Kubernetes components from RHCOS. In the enhanced version, vulnerability reporting will be based on Red Hat published security data. (ROX-10662)

So this brings me to your second question.

> Question 2: is there a roadmap for new features?

The roadmap to release RHCOS node scans using Red Hat's security data and also listing RHCOS packages is 3.73, currently scheduled for 5 December 2022.

> Question 3: how can I enable scans for CoreOS nodes?

Unfortunately, it's not possible to enable it without modifying [the code](https://github.com/stackrox/scanner/blob/c123b7aa3e21f824863b6704b9fc0850cf3ba538/ext/kernelparser/rhel/rhel.go#L34-L33). Putting it behind a toggle could be an option, but I am not sure it worth the effort since 3.71 is our next release.

Hope your questions were answered. Feel free to re-open with you want to follow up.

Otherwise, see you on 3.71!
