### ISSUE TITLE
Remove development_build image flavor

### ISSUE THREAD

**Issue by jschnath** [stackrox/stackrox#3030]
**Goal**: Reduce the number of flavors, development_build is deprecated.

- Remove flavor from `/pkg/images/default`

Internal link: https://issues.redhat.com/browse/ROX-11021

**Comment by AdwitiyaMishra** [comment]
Hi @jschnath, I would like to work on this issue. Could you please assign it to me?

**Comment by Maddosaurus** [comment]
Welcome @2022H1030042G and thanks for expressing interest into StackRox!
Feel free to take up the issue and having a look at it.
If you'd like, you can always link the branch of your fork if you have questions or need help, as the PR only counts towards Hacktober if it's opened after October 1st 😸

**Comment by Maddosaurus** [comment]
Hey @2022H1030042G!
Checking in, as Hacktoberfest has started:
Do you have any questions, or do you need any help with this?
Feel free to share any progress, roadbumps, or questions with us!

**Comment by 2022H1030042G** [comment]
Hi @Maddosaurus , thanks for reverting.
1. The thing is I'm unaware of the Go language, so if you could share the details what is the issue all about and what exactly are the modifications needed from my end?
2. As mentioned development_build is deprecated, so do I have to remove it from pkg/images/defaults/flavor.go?
3. What other methods do I have to remove & where do I have to make the changes?

**Comment by Maddosaurus** [comment]
Sure!
`flavor.go` contains the different flavors that StackRox is aware of. 
One of the flavors is `development_build`, which we don't need anymore. So that could be removed.

If you look at `flavor.go`, you will find the development_build flavor in multiple places, for example https://github.com/stackrox/stackrox/blob/master/pkg/images/defaults/flavor.go#L104  or https://github.com/stackrox/stackrox/blob/master/pkg/images/defaults/flavor.go#L32.

You would need to remove all mentions of development_build from this file. I don't know for sure if there are other places the development_build flavor is used. Most likely, there are unit tests that check for this flavor that will fail once you remove it from `flavor.go`. 
These would need to be updated as well. These tests are likely in https://github.com/stackrox/stackrox/blob/master/pkg/images/defaults/flavor_test.go.

Clone the codebase, have a look, and let us know if we can help with anything else!

**Comment by 2022H1030042G** [comment]
I have removed all the mentions of development_build from these files: flavor.go, flavor_test.go, env.go. Following are the lines from the respective files where the changes have been made:
flavor.go: Lines 31 - 35, 104 - 143, 294 - 297 are removed.
flavor_test.go: Lines 46-48, 96-100, 153-155, line 197 "development_build" is removed.
env.go: Line 13 is removed.

Let me know if there are any corrections needed?

**Comment by Maddosaurus** [comment]
That is hard to say from discussions. Could you open a Pull Request referencing this issue so we can take a look together and also see if our automated tests pass? 
Thanks! 😸

**Comment by 2022H1030042G** [comment]
Hey, I have opened up a Pull Request. You can have a look.

**Comment by Maddosaurus** [comment]
After investigating the CI results of the PR, it became apparent that we cannot remove the dev flavor at this point in time, as most processes in CI still depend on it.
I am sorry that we cannot accept this contribution as planned.
