### ISSUE TITLE
Planned to integrate prometheus exporter / grafana dashboard?

### ISSUE THREAD

**Issue by balpert89** [stackrox/stackrox#3274]
Hi

I couldn't find any infos concerning a prometheus exporter and / or a grafana dashboard. Are those things already discussed, decided on or planned?

**Comment by porridge** [comment]
Good question, @balpert89 I'll try to find out.

**Comment by stehessel** [comment]
Hi @balpert89,
Stackrox services like Central, Sensor and Scanner already expose Prometheus metrics. Depending on your deployment setup, you may need to define a Network policy to allow Prometheus to scrape the pods - you can do this via this setting in the Helm chart https://github.com/stackrox/helm-charts/blob/main/3.72.0/central-services/values-public.yaml.example#L127.

We currently don't have any plans for official dashboards, but we have some dashboards in the repo that we use for development purposes that you might take inspiration from https://github.com/stackrox/stackrox/tree/master/deploy/charts/monitoring/dashboards. You can also use the deployment scripts with `MONITORING_SUPPORT=true` (see https://github.com/stackrox/stackrox/blob/master/deploy/README.md#env-variables) to deploy a Prometheus and Grafana instance together with Stackrox.

**Comment by Maddosaurus** [comment]
We also have some additional documentation about the Prometheus setup in our downstream documentation:
https://docs.openshift.com/acs/configuration/monitor-acs.html

I'd close the issue here, but please feel free to reopen/open a new one should you have further questions or if you would like us to address a different aspect! :)
