### ISSUE TITLE
Some question about the product 

### ISSUE THREAD

**Issue by jeanphilipper** [stackrox/stackrox#3327]
Hello everyone,

My team is using this product on an Openshift infrastructure and it works great !

But, I have some questions about this :
- which components or functions create temp files and what is the mean size of created files (is there also an auto-clean function for these files ?) 
- is there a way to have access log (like apache access log) ?
- (a more Red-hat concern question) is there a way to monitor new release of different images of the product (on Red hat registries) like an RSS feed or mail notifications ?

Thank you,

~question

**Comment by msugakov** [comment]
Hi @jeanphilipper 

> which components or functions create temp files and what is the mean size of created files (is there also an auto-clean function for these files ?)

I'm not sure there's a simple answer to this one, and I definitely don't have any, but could you please share why such a question?

----

> is there a way to have access log (like apache access log) ?

I'll let colleagues who know this better than me handle it.

----

> (a more Red-hat concern question) is there a way to monitor new release of different images of the product (on Red hat registries) like an RSS feed or mail notifications ?

Apparently, there is. Try following this solution <https://access.redhat.com/solutions/4814441> but select `Red Hat Advanced Cluster Security for Kubernetes` instead of `Red Hat Ceph Storage` at the step 7.

I don't know if there's a notification mechanism in place for for community product users. One place to watch could be commit history in this location <https://github.com/stackrox/helm-charts/commits/main/opensource>.
It's worth a note that open source StackRox and ACS releases are currently published together at the same cadence.

Thanks,
Misha

**Comment by rukletsov** [comment]
@jeanphilipper, we have [audit log](https://docs.openshift.com/acs/3.72/configuration/configure-audit-logging.html) for all modifying operations and extra tracing for the built-in authorizer accessible via `roxctl central debug authz-trace`.

**Comment by jeanphilipper** [comment]
Hello @msugakov and @rukletsov,

Thank you for your replies. 

> > which components or functions create temp files and what is the mean size of created files (is there also an auto-clean function for these files ?)
> 
> I'm not sure there's a simple answer to this one, and I definitely don't have any, but could you please share why such a question?

My security departement need a lot information about our running applications like network settings, cache usage and others things. That's why, we need to know this kind of information. In fact, they want to know if there's **sensitive information in cache** and how much time are they kept in that kind of storage.

---

> Apparently, there is. Try following this solution https://access.redhat.com/solutions/4814441 but select Red Hat Advanced Cluster Security for Kubernetes instead of Red Hat Ceph Storage at the step 7.

> I don't know if there's a notification mechanism in place for for community product users. One place to watch could be commit history in this location https://github.com/stackrox/helm-charts/commits/main/opensource.
It's worth a note that open source StackRox and ACS releases are currently published together at the same cadence.

Seems to be a good idea for Github, I'll apply this.

---

> @jeanphilipper, we have [audit log](https://docs.openshift.com/acs/3.72/configuration/configure-audit-logging.html) for all modifying operations and extra tracing for the built-in authorizer accessible via roxctl central debug authz-trace.

That's what I looked for. Great !
