### ISSUE TITLE
Helm Charts not up-to-date

### ISSUE THREAD

**Issue by tha80** [stackrox/stackrox#3978]
I just noticed that the helm charts repo of stackrox have not been updated for a while. The following versions of stackrox are not available as helm chart as of now:

* 3.72.2
* 3.73.0

Could you please update the helm chart, so that the latest version is installable via helm?

**Comment by janisz** [comment]
https://github.com/stackrox/release-artifacts/pull/71
https://github.com/stackrox/release-artifacts/pull/69

**Comment by msugakov** [comment]
Hi @tha80 

Once images for these releases you mentioned are finally pushed, the Helm charts will be pushed too.
There's no magic but we need to release images in multiple locations before we can publish Helm charts, otherwise users will find charts but no images backing them. Both 3.72.2 and 3.73.0 are fresh and in the process.
For the time being you may expect new .0 versions to come out roughly every two months.

Hope this helps!

**Comment by sthadka** [comment]
The helm charts are now available.
