### ISSUE TITLE
No vulnerabilities found on latest scanner-db

### ISSUE THREAD

**Issue by krab-skunk** [stackrox/stackrox#5907]
Hello, 

I deployed stackrox (4.0.0) in our cluster, and I notice that a lot of our images are getting reported without a single vulnerabilty.
Too good to be true, i checked some with trivy and those reported with 0 issues actually got lots of them.

It says in stackrox interface : `Vulnerability definitions are up to date: 05/03/2023 | 8:11:07PM`

If i take for example this public image: `prom/mysqld-exporter:v0.13.0`, i got 0 vulnerabilities on stackrox:

```
"components": 17,
  "cves": 0,
  "fixableCves": 0,
  "lastUpdated": "2023-05-03T20:02:45.035912753Z",
  "riskScore": 1.3987501,
  "notes": [
    2,
    3
  ]
```
while trivy found 8 high and some others medium.

How can we explain such a big discrepancy, especially considering that the base image here is a basic alpine ?

Thanks a lot ;)

**Comment by RTann** [comment]
From what I can tell, Scanner is unable to determine the operating system on which this image is based (you can tell based on the notes in the results, though I'm not sure why you are seeing the numbers and not the words. 2 means `PARTIAL_SCAN_DATA` and 3 means `OS_CVES_UNAVAILABLE`. See [here](https://github.com/stackrox/stackrox/blob/4.0.0/proto/storage/image.proto#L75)).

I also verified this by pulling the image and inspecting it manually (I ran `docker save -o prom.tar prom/mysqld-exporter:v0.13.0`, unarchived it into a directory, and then inspected each of the 3 layers of the image). This image does not seem to contain any file indicating which OS on which it is based (usually look for something like `/etc/os-release`). It also did not contain any known package-manager databases (ex: `/var/lib/rpm/Packages` for the `rpm` database in RHEL-like OSes).

I looked at Trivy's results, and I found it discovered a single `gobinary` and it returned the results of that. StackRox also has the ability to discover and scan language-components, but it does not currently support Go, which is why this package was missed. Go support is in our roadmap, and we hope to have it released sometime this year.

I hope this addresses everything.

**Comment by porridge** [comment]
@krab-skunk please reopen in case you have something to add, closing as @RTann mentioned this is a planned area for improvement.
