### ISSUE TITLE
Cannot delete Violations

### ISSUE THREAD

**Issue by crimv42** [stackrox/stackrox#6013]
Hey all,

Stackrox Version: 3.72.1

I disabled a policy, yet violations are still showing for that policy when the image is not running. We want to be able to delete these alerts, but have so far been unsuccessful. 

Is there anyway to get these old policy's that no longer are running removed from the Violations list?

![image](https://github.com/stackrox/stackrox/assets/25276363/72f231c0-ff22-4615-a05a-3ca97747cfc6)
![image](https://github.com/stackrox/stackrox/assets/25276363/bbdf2dd7-2368-44cd-9908-2493859b80ef)
![image](https://github.com/stackrox/stackrox/assets/25276363/afdda897-5749-4e12-9664-42ea2ef519a0)

As you can see that policy was created over 2 years ago, but the violation still remains. There has to be a way to remove it right?

**Comment by gavin-stackrox** [comment]
Hi Daniel, that is a pretty old release. Can you update to the latest 4.0.0 and see if the behavior is still as you reported. Thanks,
-Gavin

**Comment by md2119** [comment]
@crimv42, please update to newer version. If you still see a violation, there are a couple of things I suggest since the description does not provide detailed insights:
1. Verify if the deployment exists in the database using the APIs. If the deployment exists and has not been patched, the violation will continue to show.
2. If deployment does not exist, verify if the violation is marked as RESOLVED using APIs. Resolved alerts are garbage collected by GC when it runs the next time.

To delete the violation manually, using `/v1/alerts` APIs.

<img width="1599" alt="image" src="https://github.com/stackrox/stackrox/assets/9895898/f19ef27f-487d-4c1f-bc37-4129415892d7">
