### ISSUE TITLE
How to trigger Vulnerability Scan manually ?

### ISSUE THREAD

**Issue by wonhee0410** [stackrox/stackrox#6499]
Dear All,

Thanks for your project.

I read the document and see that the vulnerability scan function will automatically scan every 4 hours.

So if I need to scan the image manually, how could I do ?

Thank you !

**Comment by janisz** [comment]
You can use roxctl as described [here](https://docs.openshift.com/acs/4.0/cli/getting-started-cli.html#:~:text=Checking%20image%20scan%20results) optionally you may want to use `--force` flag to re-pull the image.

**Comment by msugakov** [comment]
Hi @wonhee0410 
If @janisz reply was helpful, can we close this issue or do you need further info?

**Comment by wonhee0410** [comment]
> You can use roxctl as described [here](https://docs.openshift.com/acs/4.0/cli/getting-started-cli.html#:~:text=Checking%20image%20scan%20results) optionally you may want to use `--force` flag to re-pull the image.

Thank you.

So if I would like to scan individual Node manually (it contains multiple images), how could I do it by roxctl ?

**Comment by msugakov** [comment]
`roxctl` IIRC doesn't have a built-in way to identify all images on the node and scan them, therefore you'd need to script that.

Since `roxctl image scan`/`roxctl image check` commands work per image you'd need to extract information about images deployed to the node from k8s API server and feed this list one-by-one to `roxctl image scan|check` command.

**Comment by connorgorman** [comment]
Hi @wonhee0410 I hope we were able to answer your question. I'm closing this ticket due to inactivity.
