### ISSUE TITLE
roxctl cant connect to central via gRPC with no way to switch to WebSocket

### ISSUE THREAD

**Issue by shodanwashere** [stackrox/stackrox#7853]
I'm trying to perform an image scan on StackRox via roxctl, but I can't currently because of an error:
```
$ ./roxctl image check -e "stackrox.cfappsecurity.com:443" --image "ubuntu" --token-file roxapi
ERROR:  Checking image failed: could not check build-time alerts: rpc error: code = Unavailable desc = transport: receiving gRPC response from remote endpoint: 464 , content-type . Retrying after 3 seconds...
```
The problem with this seems to be the communication between roxctl and the Central service, which, in my cluster, is sistting behind an Amazon ALB, which does not support gRPC. Is there a way of connecting to Central via roxctl, using WebSocket instead of gRPC?

**Comment by Maddosaurus** [comment]
Hi @shodanwashere!
Thanks for checking in. Yes, you can use WebSockets instead of gRPC if your LoadBalancer doesn't support it.
You can prefix the address of central with `wss://` to switch to WebSockets 😄 
Example:
`roxctl sensor generate k8s --central wss://stackrox-central.example.com:443` 

Feel free to reopen/comment on this issue should you have further problems!
