### ISSUE TITLE
Question about Helm setup with central.persistence value

### ISSUE THREAD

**Issue by dan-m8t** [stackrox/stackrox#8509]
Hello,

right now I am stumbling across this error:

```
FATAL ERROR:
Starting from 4.1, we stop creating central PVC during installation. Databases and
persistent data are stored in Central DB or external databases. You may use `--set
central.persistence.none=true` during Helm install to override default persistence config. Got
map[hostPath:<nil> none:<nil> persistentVolumeClaim:map[claimName:<nil> createClaim:<nil> size:<nil>
storageClass:<nil> volume:map[volumeSpec:<nil>]]]
```

As the error states when I set `central.persistence.none=true` the error disappears and the setup works just fine. But what I dont really understand why such warning, when itself states that databases and persistent data is stored in Central DB? I don't get why then `central.persistence.none=true` isn't the default? Can I safely ignore this with the mentioned value?

Thanks

Dan

**Comment by c-du** [comment]
In 4.1, we are in transition from PVC attached to Central to external Central DB. The PVC is now attached to Central DB instead of Central. However, we still have customer upgrading from earlier versions and they do not have central.persistence.none settings. We still need Central Attached PVC for some persistent data in earlier versions. We will remove this setting and default to not have Central attached PVC once we phase out the requirements of upgrades.

Hope this helps.
